import { lazy } from 'react';

export const MEASURE_MENUS = [
  {
    id: 'record',
    no: 0,
    title: '일반 영상 녹화',
    desc: '카메라 녹화 및 저장',
    icon: 'REC',
    status: 'ready',
    component: lazy(() => import('./menus/RecordMeasure.jsx')),
  },
  {
    id: 'body',
    no: 0.5,
    title: '신체 정보',
    desc: '키, 몸무게, 혈압 입력 및 분석',
    icon: 'BIO',
    status: 'ready',
    component: lazy(() => import('./menus/BodyInfoMeasure.jsx')),
  },
  {
    id: 'posture',
    no: 1,
    title: '자세·체형 측정',
    desc: 'Posture score, Body age, CoG, Ghosting',
    icon: 'BAL',
    status: 'ready',
    component: lazy(() => import('./menus/PostureMeasure.jsx')),
  },
  {
    id: 'rom',
    no: 2,
    title: 'ROM 좌우 비교',
    desc: '관절 가동범위 및 좌우 대칭',
    icon: 'ROM',
    status: 'planned',
  },
  {
    id: 'jump',
    no: 3,
    title: '점프 & RSI',
    desc: '반동점프, 반응탄성, 고속영상/수동 분석',
    icon: 'JMP',
    status: 'ready',
    component: lazy(() => import('./menus/JumpAnalysisHub.jsx')),
  },
  {
    id: 'onerm',
    no: 5,
    title: '1RM 추정',
    desc: '벤치, 스쿼트, 데드리프트 무게와 반복수',
    icon: '1RM',
    status: 'ready',
    component: lazy(() => import('./menus/OneRMEstimate.jsx')),
  },
  {
    id: 'throw',
    no: 6,
    title: '스로잉 & 던지기',
    desc: '가속도, 파워, 속도',
    icon: 'PWR',
    status: 'planned',
  },
  {
    id: 'vbt',
    no: 7,
    title: 'VBT',
    desc: '속도 기반 트레이닝, 거리/시간',
    icon: 'VBT',
    status: 'ready',
    component: lazy(() => import('./menus/VbtMeasure.jsx')),
  },
  {
    id: 'lifting',
    no: 8,
    title: '역도',
    desc: '스내치, 클린, 바벨 추적',
    icon: 'BAR',
    status: 'ready',
    component: lazy(() => import('./menus/LiftingMeasure.jsx')),
  },
  {
    id: 'swing',
    no: 9,
    title: '스윙',
    desc: '골프, 배트, ROM, 속도',
    icon: 'SWG',
    status: 'planned',
  },
  {
    id: 'gait',
    no: 10,
    title: '보행 & 러닝',
    desc: '측면/정면, 각도, 케이던스, 주기 분석',
    icon: 'RUN',
    status: 'ready',
    component: lazy(() => import('./menus/GaitAnalysisHub.jsx')),
  },
  {
    id: 'timer',
    no: 11,
    title: '초시계·메트로놈',
    desc: '초시계, 타이머, 메트로놈',
    icon: 'TMR',
    status: 'ready',
    component: lazy(() => import('./menus/TimerTool.jsx')),
  },
];
